# Generated by Django 4.2.7 on 2023-11-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email клиента')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, max_length=300, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_name', models.CharField(max_length=200, verbose_name='Имя рассылки')),
                ('time', models.TimeField(verbose_name='Время рассылки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=25, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('started', 'Запущена'), ('created', 'Создана'), ('done', 'Завершена')], max_length=25, verbose_name='Статус')),
                ('send_mail_subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('send_mail_message', models.TextField(max_length=1500, verbose_name='Текст письма')),
                ('clients_list', models.ManyToManyField(related_name='mailings', to='mailing.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing', models.DateTimeField(verbose_name='Время последней попытки')),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], max_length=25, verbose_name='Статус')),
                ('clients_full_name', models.TextField(verbose_name='ФИО клиентов')),
                ('clients_email', models.TextField(verbose_name='email клиентов')),
                ('mailing_name', models.CharField(max_length=200, verbose_name='Имя рассылки')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='mailings_list',
            field=models.ManyToManyField(related_name='clients', to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
