# Generated by Django 4.2.7 on 2023-11-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'ordering': ('id',), 'verbose_name': 'Лог рассылки', 'verbose_name_plural': 'Логи рассылок'},
        ),
    ]
