# Generated by Django 4.2.7 on 2023-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailinglog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mailings_list',
            field=models.ManyToManyField(blank=True, related_name='clients', to='mailing.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients_list',
            field=models.ManyToManyField(blank=True, related_name='mailings', to='mailing.client', verbose_name='Клиент'),
        ),
    ]
