# Generated by Django 4.2.7 on 2023-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='Ежедневная', max_length=25, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('started', 'Создана'), ('created', 'Запущена'), ('done', 'Завершена')], default='Создана', max_length=25, verbose_name='Статус'),
        ),
    ]
