# Generated by Django 4.2.7 on 2023-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients_list',
            field=models.ManyToManyField(related_name='mailings', to='mailing.client', verbose_name='Клиент'),
        ),
    ]
